Require hashes for all pip installs (#1871)
* Require hashes for all pip installs

* clean up from bad merge

* fix test

* Generate requirements

* copy in dockerfile

* copy in dockerfile

* spotless

* Fix dockerfiles

* Add some more dependencies

* Generate for pubsub-to-mongo

* Add back accidentally deleted file

* test fix

* test fix

* feeeedback

* remove jinja

diff --git a/plugins/core-plugin/src/main/resources/Dockerfile-template-yaml b/plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
--- a/plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
+++ b/plugins/core-plugin/src/main/resources/Dockerfile-template-yaml
@@ -6,8 +6,6 @@ FROM ${basePythonContainerImage} as python-base
 # Build args
 ARG WORKDIR=/template
 ARG REQUIREMENTS_FILE=requirements.txt
-ARG BEAM_VERSION=${beamVersion}
-ARG BEAM_PACKAGE=apache-beam[dataframe,gcp,test,yaml]==$BEAM_VERSION
 ARG PY_VERSION=${pythonVersion}
 
 # Copy template files to /template
@@ -16,18 +14,15 @@ ${filesToCopy}
 ${directoriesToCopy}
 WORKDIR $WORKDIR
 
-# Create requirements.txt file if not provided
-RUN if ! [ -f requirements.txt ] ; then echo "$BEAM_PACKAGE" > requirements.txt ; fi
+# Throw if requirements.txt file not provided
+RUN if ! [ -f requirements.txt ] ; then >&2 echo "error: no requirements.txt file found" && exit 1 ; fi
 
 # Install dependencies to launch the pipeline and download to reduce startup time
-# Remove Jinja2 dependency once YAML templatization support is added to Beam
 # TODO - remove `pip uninstall apache-beam` line when repo is upgraded to Beam 2.59.0
 RUN python -m venv /venv \
     && /venv/bin/pip uninstall apache-beam -y \
-    && /venv/bin/pip install --no-cache-dir --upgrade pip setuptools \
-    && /venv/bin/pip install --no-cache-dir -U -r $REQUIREMENTS_FILE \
-    && /venv/bin/pip install --no-cache-dir -U Jinja2 \
-    && /venv/bin/pip download --no-cache-dir --dest /tmp/dataflow-requirements-cache -r $REQUIREMENTS_FILE \
+    && /venv/bin/pip install --require-hashes --no-cache-dir -U -r $REQUIREMENTS_FILE \
+    && /venv/bin/pip download --require-hashes --no-cache-dir --dest /tmp/dataflow-requirements-cache -r $REQUIREMENTS_FILE \
     && rm -rf /usr/local/lib/python$PY_VERSION/site-packages  \
     && mv /venv/lib/python$PY_VERSION/site-packages /usr/local/lib/python$PY_VERSION/
 
