Fix dockerfiles

diff --git a/plugins/core-plugin/src/main/resources/Dockerfile-template-python b/plugins/core-plugin/src/main/resources/Dockerfile-template-python
--- a/plugins/core-plugin/src/main/resources/Dockerfile-template-python
+++ b/plugins/core-plugin/src/main/resources/Dockerfile-template-python
@@ -8,6 +8,8 @@ WORKDIR $WORKDIR
 ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt
 ENV FLEX_TEMPLATE_PYTHON_PY_FILE=main.py
 
+RUN if ! [ -f requirements.txt ] ; then >&2 echo "error: no requirements.txt file found" && exit 1 ; fi
+
 RUN pip install -U -r --require-hashes $FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE
 RUN pip download --no-cache-dir --dest /tmp/dataflow-requirements-cache -r $FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE
 
diff --git a/plugins/core-plugin/src/main/resources/Dockerfile-template-xlang b/plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
--- a/plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
+++ b/plugins/core-plugin/src/main/resources/Dockerfile-template-xlang
@@ -17,7 +17,7 @@ ${directoriesToCopy}
 WORKDIR $WORKDIR
 
 # Throw if requirements.txt file not provided
-RUN if ! [ -f requirements.txt ] ; >&2 echo "error: no requirements.txt file found" && exit 1 ; fi
+RUN if ! [ -f requirements.txt ] ; then >&2 echo "error: no requirements.txt file found" && exit 1 ; fi
 
 # Install dependencies to launch the pipeline and download to reduce startup time
 RUN python -m venv /venv \
